### ISSUE TITLE
多次缓存数据后，本地缓存数据会混乱

### ISSUE THREAD

**Issue by myDonghao** [CoderMaoWX/WXNetworkingSwift#2]
我看沙盒文件是缓存了多个文件。

👉👉👉已发出网络请求= http://xxxxxxxx/api/product/function/page

❤️❤️❤️请求接口地址【Debug】= http://xxxxxxxx/api/product/function/page

请求参数json= **{"functionId":"1646771757623144449","size":9999,"productModelId":"1647846401360912386"}**

✅✅✅请求接口地址【Debug】= http://xxxxxxxx/api/product/function/page

请求参数json= **{"functionId":"1646771757623144449","size":9999,"productModelId":"1647846401360912386"}**

👉👉👉已发出网络请求= http://xxxxxxxxxx/api/product/function/page

❤️❤️❤️请求接口地址【Debug】= http://xxxxxxxxx/api/product/function/page

请求参数json= **{"productModelId":"1647846401360912386","size":9999,"functionId":"1646771757623144449"}**

✅✅✅请求接口地址【Debug】= http://xxxxxxxxxx/api/product/function/page

请求参数json= **{"productModelId":"1647846401360912386","size":9999,"functionId":"1646771757623144449"}**

**Comment by myDonghao** [comment]
原因感觉像是cacheKey的问题。字典转json之后是无序的，同一个参数的jsonString可能生成了多条

**Comment by myDonghao** [comment]
修改了源码里面的json转jsonstring的option 为 sortkeys，应该可以了

**Comment by CoderMaoWX** [comment]
已修改，感谢提醒！
